### ISSUE TITLE
Test Kitchen fails 

### ISSUE THREAD

**Issue by gsaslis** [arussel/chef-java-wrapper#4]
I've fixed a number of problems - due to outdated links, etc. - and updated test-kitchen and chef to latest versions successfully, but for some reason, test kitchen now hangs in the bash script that's supposed to run 'play stage' in the test cookbook. 

I've spent hours looking into it, and it looks like it's probably related to the inability to correctly set the environment when using the bash / execute resource when running as different user than the one running the chef-client / chef-solo -- or when running sudo as user vagrant... 
Some links that might be useful: 
- http://stackoverflow.com/questions/17614372/how-to-make-chef-execute-with-a-specific-user-and-load-its-environment-values
- http://airbladesoftware.com/notes/three-chef-gotchas/

After all this time looking into it, I really feel we should just remove the play framework stuff from the IT tests, since it's beyond the scope of the cookbook tests anyway.. 

imho, all we should test is the java_wrapper resource and it's already being tested once (with jetty), so there's no need to test it again with the play framework stuff (??)
I feel that can be safely removed, so I'll open another PR to handle this... 

What do you think guys?

**Comment by arussel** [comment]
@gsaslis completely agree.

**Comment by gsaslis** [comment]
closed by #5
